### PR TITLE
JDO for movies and sessions

### PR DESCRIPTION
**Pull request by kuu22**
What's needed for the first sprint regarding DB is done.

### CODE REVIEW

**Comment by WysokiStudent** [comment]
This fails to compile on Ubuntu 18 due to a slash hack inside "Server" and is also missing a necessary command that sets up the database. I pushed the fixes to my branch. Would you care to look at it?
-Alex

**Comment by kuu22** [comment]
It will compile but it won't connect, it needs the double slash. What JDK are you running? It worked for me last semester with OpenJDK 8 in 18.04 @WysokiStudent

**Comment by WysokiStudent** [comment]
I'm running OpenJDK-11

**Comment by kuu22** [comment]
Try doing `"/" + "/" + args[0]` (dirty fix but it should work)

**Pull request merged**
